version: '3.8'
services:
  mrm_nn_photo:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    build: service
    environment:
      - SERVICE_NAME=МРМ НН фото (debug)
      - SERVICE_URL=https://example.com
      - REGULAR_SLEEP=1
      - ERROR_SLEEP=59
      - TELEGRAM_CHAT=place_there_your_chat_it
      - TELEGRAM_BOT_TOKEN=place_there_your_bot_token